#!/usr/bin/env bun
import { execFileSync, spawn } from 'node:child_process'
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { basename, join, relative } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const DS_DIR = join(ROOT, 'design-systems')
const LIB_DIR = join(ROOT, '..', 'lib')
// Published design systems live at the repo root, beside the lib.
const ROOT_DS = [join(ROOT, '..', 'ui')]
const SWITCHER = join(ROOT, 'components', 'demo-switcher')
const PEERS_FILE = join(ROOT, 'components', 'demo-switcher', '.peers.json')
const TEMP_CONFIG = '.modo.config.ts'
const SITE_DIR = join(ROOT, 'dist')
const BASE_PORT = 5173
// By path, not `bunx modo`: before the lib is built its bin has nothing to
// run, and bunx then fetches the unrelated `modo` from npm. Node runs Vite
// directly, so a signal reaches it instead of a wrapper.
const MODO_CLI = join(LIB_DIR, 'dist', 'cli.js')
// The path the built site is served under, e.g. `/modo/` on a GitHub Pages project site.
const SITE_BASE = process.env.SITE_BASE ?? '/'

const build = process.argv.includes('--build')
const wanted = process.argv.slice(2).filter(a => a !== '--build')
// Dir husks can outlive their tracked files (a merge-deleted DS leaves .modo-tmp/ behind).
const dirs = new Map(
  [...readdirSync(DS_DIR).map(name => join(DS_DIR, name)), ...ROOT_DS]
    .filter(dir => existsSync(join(dir, 'modo.config.ts')))
    .map(dir => [basename(dir), dir]),
)
const all = [...dirs.keys()].sort()
const targets = wanted.length > 0 ? all.filter(n => wanted.includes(n)) : all
if (targets.length === 0) {
  process.stderr.write(`no design systems found${wanted.length > 0 ? ` matching: ${wanted.join(', ')}` : ''}\n`)
  process.stderr.write('usage: bun scripts/run-design-systems.ts [--build] [name ...]\n')
  process.exit(1)
}

// The temp config re-exports the real one with the switcher appended, so a
// design system that ships its own panel items (ui's theme switcher) keeps
// them instead of having `panel` overwritten.
function withSwitcher(dir: string) {
  const item = JSON.stringify({ label: 'Switcher', component: relative(dir, SWITCHER) })
  return [
    '// generated by scripts/run-design-systems.ts — safe to delete',
    "import base from './modo.config'",
    '',
    'export default {',
    '  ...base,',
    `  panel: { items: [...(base.panel?.items ?? []), ${item}] },`,
    '}',
    '',
  ].join('\n')
}
const dirOf = (name: string) => dirs.get(name)!

function removeTemp(names: string[]) {
  for (const name of names) rmSync(join(dirOf(name), TEMP_CONFIG), { force: true })
  rmSync(PEERS_FILE, { force: true })
}

if (!existsSync(MODO_CLI)) execFileSync('bun', ['run', 'build'], { cwd: LIB_DIR, stdio: 'inherit' })
// A previous run killed hard leaves its temp configs behind.
removeTemp(all)
const peerUrl = (name: string, i: number) => (build ? `${SITE_BASE}${name}/` : `http://127.0.0.1:${BASE_PORT + i}/`)
writeFileSync(
  PEERS_FILE,
  JSON.stringify(
    targets.map((name, i) => ({ name, url: peerUrl(name, i) })),
    null,
    2,
  ),
)
for (const name of targets) writeFileSync(join(dirOf(name), TEMP_CONFIG), withSwitcher(dirOf(name)))

function buildSite() {
  rmSync(SITE_DIR, { recursive: true, force: true })
  mkdirSync(SITE_DIR)
  for (const name of targets) {
    // --out: a published design system's own dist/ holds its package build.
    const args = ['build', '--config', TEMP_CONFIG, '--base', `${SITE_BASE}${name}/`, '--out', join(SITE_DIR, name)]
    execFileSync('node', [MODO_CLI, ...args], { cwd: dirOf(name), stdio: 'inherit' })
  }
  writeFileSync(
    join(SITE_DIR, 'index.html'),
    `<!doctype html><title>modo</title><meta http-equiv="refresh" content="0; url=${targets[0]}/">\n`,
  )
}

// Each server takes its port strictly, so a stale one from another run fails
// loudly instead of being silently replaced.
function serve() {
  const children = targets.map((name, i) =>
    spawn('node', [MODO_CLI, 'dev', '--config', TEMP_CONFIG], {
      cwd: dirOf(name),
      stdio: 'inherit',
      env: { ...process.env, MODO_PORT: String(BASE_PORT + i) },
    }),
  )
  const cleanup = () => {
    for (const child of children) child.kill('SIGTERM')
    removeTemp(targets)
    process.exit(0)
  }
  for (const signal of ['SIGINT', 'SIGTERM', 'SIGHUP'] as const) process.on(signal, cleanup)
}

if (build) {
  try {
    buildSite()
  } finally {
    removeTemp(targets)
  }
} else {
  serve()
}
