#!/usr/bin/env bun
import { execFileSync, execSync, spawn } from 'node:child_process'
import { existsSync, mkdirSync, readdirSync, renameSync, rmSync, unlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const DS_DIR = join(ROOT, 'design-systems')
const PEERS_FILE = join(ROOT, 'components', 'demo-switcher', '.peers.json')
const TEMP_CONFIG = '.modo.config.ts'
const SITE_DIR = join(ROOT, 'dist')
// By path, not `bunx modo`: on a fresh install the lib's bin is linked before
// its dist exists, and bunx then fetches the unrelated `modo` from npm.
const MODO_CLI = join(ROOT, '..', 'lib', 'dist', 'cli.js')
// The path the built site is served under, e.g. `/modo/` on a GitHub Pages project site.
const SITE_BASE = process.env.SITE_BASE ?? '/'

const build = process.argv.includes('--build')
const wanted = process.argv.slice(2).filter(a => a !== '--build')
// dir husks can outlive their tracked files (a merge-deleted DS leaves .modo-tmp/ behind)
const all = readdirSync(DS_DIR, { withFileTypes: true })
  .filter(e => e.isDirectory() && existsSync(join(DS_DIR, e.name, 'modo.config.ts')))
  .map(e => e.name)
  .sort()
const targets = wanted.length > 0 ? all.filter(n => wanted.includes(n)) : all
if (targets.length === 0) {
  process.stderr.write(`no design systems found${wanted.length > 0 ? ` matching: ${wanted.join(', ')}` : ''}\n`)
  process.stderr.write('usage: bun scripts/run-design-systems.ts [--build] [name ...]\n')
  process.exit(1)
}

for (const e of readdirSync(DS_DIR, { withFileTypes: true })) {
  if (!e.isDirectory()) continue
  try {
    unlinkSync(join(DS_DIR, e.name, TEMP_CONFIG))
  } catch {}
}

const items = [{ label: 'Switcher', component: '../../components/demo-switcher' }]
// The temp config re-exports the real one with the switcher appended, so a
// design system that ships its own panel items (ui's theme switcher) keeps
// them instead of having `panel` overwritten.
const withSwitcher = (): string =>
  [
    '// generated by scripts/run-design-systems.ts — safe to delete',
    "import base from './modo.config'",
    '',
    'export default {',
    '  ...base,',
    `  panel: { items: [...(base.panel?.items ?? []), ...${JSON.stringify(items)}] },`,
    '}',
    '',
  ].join('\n')

const peerUrl = (name: string, i: number) => (build ? `${SITE_BASE}${name}/` : `http://127.0.0.1:${5173 + i}/`)
writeFileSync(
  PEERS_FILE,
  JSON.stringify(
    targets.map((name, i) => ({ name, url: peerUrl(name, i) })),
    null,
    2,
  ),
)
for (const name of targets) writeFileSync(join(DS_DIR, name, TEMP_CONFIG), withSwitcher())

function removeTemp() {
  for (const name of targets)
    try {
      unlinkSync(join(DS_DIR, name, TEMP_CONFIG))
    } catch {}
  try {
    unlinkSync(PEERS_FILE)
  } catch {}
}

function buildSite() {
  rmSync(SITE_DIR, { recursive: true, force: true })
  mkdirSync(SITE_DIR)
  for (const name of targets) {
    const cwd = join(DS_DIR, name)
    execFileSync('node', [MODO_CLI, 'build', '--config', TEMP_CONFIG, '--base', `${SITE_BASE}${name}/`], {
      cwd,
      stdio: 'inherit',
    })
    renameSync(join(cwd, 'dist'), join(SITE_DIR, name))
  }
  writeFileSync(
    join(SITE_DIR, 'index.html'),
    `<!doctype html><title>modo</title><meta http-equiv="refresh" content="0; url=${targets[0]}/">\n`,
  )
}

function serve() {
  // Kill any stale `modo dev` processes from a previous run that
  // didn't clean up. Match the lib's `node .../modo dev` argv (not
  // just `bunx modo`) since Vite orphans can outlive their bunx parent.
  try {
    execSync("pkill -f 'modo dev' 2>/dev/null", { stdio: 'ignore' })
    execSync('sleep 0.5', { stdio: 'ignore' })
  } catch {}

  const children = targets.map((name, i) =>
    spawn('bunx', ['modo', 'dev', '--config', TEMP_CONFIG], {
      cwd: join(DS_DIR, name),
      stdio: 'inherit',
      env: { ...process.env, MODO_PORT: String(5173 + i) },
    }),
  )
  const cleanup = () => {
    for (const child of children)
      try {
        child.kill('SIGTERM')
      } catch {}
    removeTemp()
    process.exit(0)
  }
  process.on('SIGINT', cleanup)
  process.on('SIGTERM', cleanup)
}

if (build) {
  try {
    buildSite()
  } finally {
    removeTemp()
  }
} else {
  serve()
}
