/**
 * Renders `createTheme({ cssVariables: true })` and writes MUI's real default
 * theme into tokens/*.css. Run: `bun scripts/extract-tokens.ts`. The per-file
 * breakdown (colors/spacing/radius/typography) is documented in README.md.
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createTheme } from '@mui/material/styles'

const dsRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))
const tokensDir = resolve(dsRoot, 'tokens')
const HEADER = '/* generated by scripts/extract-tokens.ts — do not edit */\n'

const theme = createTheme({ cssVariables: true })

function flattenVars(obj: object, prefix = ''): Array<[string, string]> {
  const out: Array<[string, string]> = []
  for (const [key, value] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key
    if (value && typeof value === 'object') {
      out.push(...flattenVars(value, path))
    } else if (typeof value === 'string') {
      out.push([path, value])
    }
  }
  return out
}

const VAR_RE = /^var\((--[a-zA-Z0-9-]+),\s*(.+)\)$/

// `vars` is typed optional unless CssThemeVariables is augmented; cssVariables: true sets it
const paletteVars = flattenVars(theme.vars!.palette)
const colorLines: string[] = []
for (const [path, raw] of paletteVars) {
  if (/(Channel|Opacity)$/.test(path)) continue // "r g b" triplets and alpha numbers, not CSS colors
  if (raw.includes('undefined')) continue // reads a skipped Channel var that has no fallback
  const m = raw.match(VAR_RE)
  if (!m) continue
  const name = m[1]!
  const fallback = m[2]!
  if (name !== `--mui-palette-${path.replace(/\./g, '-')}`) continue // naming must match MUI's own
  colorLines.push(`  ${name}: ${fallback};`)
}

const spacingFallback = theme.spacing(1).match(/var\(--mui-spacing,\s*([\d.]+)px\)/)
const spacingUnit = spacingFallback ? Number(spacingFallback[1]) : 8
const spacingSteps = [...Array(13).keys(), 0.5, 1.5, 2.5, 3.5].sort((a, b) => a - b)
const spacingLines = spacingSteps.map(n => `  --space-${String(n).replace('.', '_')}: ${n * spacingUnit}px;`)

const unit = Number(theme.shape.borderRadius)
const radiusLines = [
  `  --radius-sm: ${unit}px;`,
  `  --radius-md: ${unit * 2}px;`,
  `  --radius-lg: ${unit * 4}px;`,
  `  --radius-full: 9999px;`,
]

const t = theme.typography
const variants = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'body1', 'body2', 'caption'] as const
const typographyLines = [`  --font-family: ${t.fontFamily};`]
for (const name of variants) {
  const v = t[name]
  typographyLines.push(`  --text-${name}: ${v.fontSize};`)
  if (v.fontWeight !== undefined) typographyLines.push(`  --text-${name}-weight: ${v.fontWeight};`)
}

await mkdir(tokensDir, { recursive: true })
const files: Array<[string, string[]]> = [
  ['colors.css', colorLines],
  ['spacing.css', spacingLines],
  ['radius.css', radiusLines],
  ['typography.css', typographyLines],
]
for (const [name, lines] of files) {
  const body = `:root {\n${lines.join('\n')}\n}\n`
  await writeFile(resolve(tokensDir, name), HEADER + body, 'utf8')
  console.log(`extract-tokens: tokens/${name} — ${lines.length} vars`)
}
